version: '3'
services:
  redis-server:
    image: redis
  scrapper:
    build: .
    command: 'ruby ./scrap_sources.rb'
    environment:
      - REDIS_URL=redis://redis-server:6379/0
      - ARTIFACTS_ENV=docker_development
      - DATA_API_BASE=http://data_api:3000
    volumes:
      - .:/usr/src/artifacts_scrapper
    depends_on:
      - data_api
      - redis-server
  data_api:
    image: davidgeismar/artifacts_data_api:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/artifacts_data_api
    environment:
      - RAILS_ENV=docker_development
      - SECRET_KEY_BASE=docker_development_secret
  sidekiq:
    build: .
    command: 'bundle exec sidekiq -r ./artifacts_scrapper.rb 2>&1 | tee ./log/sidekiq.log'
    volumes:
      - ./:/usr/src/artifacts_scrapper
    environment:
      - REDIS_URL=redis://redis-server:6379/0
      - ARTIFACTS_ENV=docker_development
      - DATA_API_BASE=http://data_api:3000
    depends_on:
      - redis-server
      - data_api
