version: '3'
services:
  redis-server:
    image: redis
    restart: always
  scrapper:
    image: davidgeismar/artifacts-scrapper:without-db
    command: "bundle exec rake scrap_sources:scrap\"[['christies'],nil,[2019]]\""
    environment:
      - REDIS_URL=redis://redis-server:6379/0
      - ARTIFACTS_ENV=docker_development
      - DATA_API_BASE=http://data_api:3000
    restart: always
    depends_on:
      - data_api
      - redis-server
  data_api:
    restart: always
    image: davidgeismar/artifacts_data_api:latest
    command: 'rails server -b 0.0.0.0'
    environment:
      - RAILS_ENV=docker_development
      - SECRET_KEY_BASE=docker_development_secret
  sidekiq:
    restart: always
    image: davidgeismar/artifacts-scrapper:without-db
    command: 'bundle exec sidekiq -r ./artifacts_scrapper.rb 2>&1 | tee ./log/sidekiq.log'
    environment:
      - REDIS_URL=redis://redis-server:6379/0
      - ARTIFACTS_ENV=docker_development
      - DATA_API_BASE=http://data_api:3000
    depends_on:
      - redis-server
      - data_api
