source 'https://rubygems.org'

gem 'rspec'
gem 'activesupport'
gem 'activerecord'
gem 'standalone_migrations', '7.1.0'
gem 'pg'
gem 'httparty'
gem 'nokogiri'
gem 'mechanize'
gem 'pry-byebug'
gem 'sidekiq'
gem 'dotenv'
